[book]
authors = ["HugoPhi"]
language = "zh"
multilingual = false
src = "src"
title = "Yunming Hu's Blog"

[output.html]
theme = "theme"
default-theme = "rust"
git-repository-url = "https://github.com/HugoPhi"
git-repository-icon = "fa-github"

[preprocessor.katex]
